name: Bandit Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-analysis:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Python application from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python and specify the version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install Bandit
    - name: Install Bandit
      run: pip install bandit

    # Step 4: Run Bandit to perform analysis
    - name: Run Bandit Analysis
      run: bandit -r . -f txt -o bandit-report.txt

    # Step 5: Upload the Bandit report as an artifact
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.txt

    # Step 6: Optimize to avoid false positives (optional)
    # Add configurations to `.bandit` config file if needed
    - name: Add Bandit Configuration (optional)
      if: ${{ always() }}
      run: |
        echo "[bandit]" > .bandit
        echo "skips: B101,B102" >> .bandit  # Example of skipping specific tests
        cat .bandit
